project:
  type: website
  output-dir: docs


website:
  title: "Zane Sano Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About Me"
      - href: portfolio-project/project-portfolio.qmd
        text: "Portfolio Project"
format:
  html:
    theme: cyborg
    css: styles.css
    toc: true

editor: visual